// export const TOP_GAINER_ALL_DAY_TYPE="TOP_GAINER_TOP_LOSER_ALL_DAY_TYPE"
// export const TOP_GAINER_ALL_DAY_IS_SELETED="TOP_GAINER_ALL_DAY_IS_SELETED" 
export const HIGH_WEEK_52_ALL_GROUP_NAME="HIGH_WEEK_52_ALL_GROUP_NAME" 
export const HIGH_WEEK_52_ALL_GROUP_IS_SELETED="HIGH_WEEK_52_ALL_GROUP_IS_SELETED" 