export const DOMESTIC_INDEX='DOMESTIC_INDEX'
export const INTERNATIONAL_INDEX='INTERNATIONAL_INDEX'
export const DEAL='DEAL'
export const WEEK_HEIG_52='WEEK_HEIG_52'
export const WEEK_LOW_52='WEEK_LOW_52'
export const SECTOR='SECTOR'
export const ALL_HIGH='ALL_HIGH'
export const ALL_LOW='ALL_LOW'
///
export const TOP_LOSER='TOP_LOSER'
export const TOP_GAINER='TOP_GAINER'
export const EXCHANGE_HOLIDAY='EXCHANGE_HOLIDAY' 
export const ADVANCE_DECLINE='ADVANCE_DECLINE' 
export const FILL_ACTIVITY='FILL_ACTIVITY' 
export const LOW_PRICE_HIGH_VOLU='LOW_PRICE_HIGH_VOLU' 
export const OUT_UNDER_PERFORMERS='OUT_UNDER_PERFORMERS' 
//
export const FII_DII_ACTIVITY='FII_DII_ACTIVITY' 
export const ACTIVE_COMPANIES='ACTIVE_COMPANIES' //ActiveCompanies





// ============Layer Two

export const DOMESTIC_INDEX_LAYER_TWO='DOMESTIC_INDEX_LAYER_TWO' 

