export const ALL_TIME_LOW_ALL_LIST = 'ALL_TIME_LOW_ALL_LIST'
export const ALL_TIME_LOW_IS_SELETED = 'ALL_TIME_LOW_IS_SELETED'
export const ALL_TIME_LOW_ALL_GROUP = 'ALL_TIME_LOW_ALL_GROUP'
export const ALL_TIME_LOW_IS_SELETED_GROUP = 'ALL_TIME_LOW_IS_SELETED_GROUP'