export const ALL_TIME_HIGH_ALL_LIST = 'ALL_TIME_HIGH_ALL_LIST'
export const ALL_TIME_HIGH_IS_SELETED = 'ALL_TIME_HIGH_IS_SELETED'
export const ALL_TIME_HIGH_ALL_GROUP = 'ALL_TIME_HIGH_ALL_GROUP'
export const ALL_TIME_HIGH_ALL_GROUP_IS_SELETED = 'ALL_TIME_HIGH_ALL_GROUP_IS_SELETED'