// export const TOP_GAINER_ALL_DAY_TYPE="TOP_GAINER_TOP_LOSER_ALL_DAY_TYPE"
// export const TOP_GAINER_ALL_DAY_IS_SELETED="TOP_GAINER_ALL_DAY_IS_SELETED" 
export const FII_DII_ALL_GROUP_NAME="FII_DII_ALL_GROUP_NAME" 
export const FII_DII_ALL_GROUP_IS_SELETED="FII_DII_ALL_GROUP_IS_SELETED"