export const COMPANY_DETAILS_FOR_HOME='COMPANY_DETAILS_FOR_HOME'
export const COMPANY_DETAILS_PRICE_VOLUME='COMPANY_DETAILS_PRICE_VOLUME'
export const COMPANY_DETAILS_SCORE='COMPANY_DETAILS_SCORE'
export const COMPANY_DETAILS_EVENT='COMPANY_DETAILS_EVENT'
export const DETAILS_EVENT='DETAILS_EVENT'
export const COMPANY_FINANCIALS='COMPANY_FINANCIALS' //Financials
export const COMPANY_FINANCIALS_SELECTED='COMPANY_FINANCIALS_SELECTED' //Financials